apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-mcp-service
  labels:
    app: weather-mcp-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-mcp-service
  template:
    metadata:
      labels:
        app: weather-mcp-service
    spec:
      containers:
      - name: weather-mcp
        image: weather-mcp-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env: []
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        # livenessProbe:
        #   httpGet:
        #     path: /weather
        #     port: 8080
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /weather
        #     port: 8080
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: weather-mcp-service
  labels:
    app: weather-mcp-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: weather-mcp-service
